# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFB1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fB1(self):
    self.driver.get("https://www.facebook.com/stanleysLoL/community")
    self.driver.set_window_size(1440, 877)
    self.driver.find_element(By.CSS_SELECTOR, ".s1tcr66n > .d2edcug0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bp9cbjyn:nth-child(2) > .d2edcug0").click()
  
